FileVersion = 1
Projects = {CppInterop = {Path = "."}}

[Workspace]
StartupProject = "CppInterop"

[Configs.Debug.Win64]
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
