FileVersion = 1
Projects = {HelloWorld = {Path = "HelloWorld"}, CInterop = {Path = "CInterop"}}

[Workspace]
StartupProject = "CInterop"

[Configs.Test.Win32]
ConfigSelections = {corlib = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {corlib = {Config = "Debug"}}
