FileVersion = 1
Projects = {HelloWorld = {Path = "HelloWorld"}, CInterop = {Path = "CInterop"}, VectorMath = {Path = "VectorMath"}, Pointer = {Path = "Pointer"}}

[Workspace]
StartupProject = "Pointer"
