FileVersion = 1
Projects = {HelloWorld = {Path = "HelloWorld"}, CInterop = {Path = "CInterop"}, VectorMath = {Path = "VectorMath"}, CppInterop = {Path = "CppInterop"}}

[Workspace]
StartupProject = "CppInterop"
