FileVersion = 1
Projects = {HelloWorld = {Path = "HelloWorld"}, CInterop = {Path = "CInterop"}, VectorMath = {Path = "VectorMath"}, Pointer = {Path = "Pointer"}, Enum = {Path = "Enum"}, ImGuiExample = "*", ImGuiImplSDL = "*", ImGuiImplOpenGL3 = "*", ImGuiExample = {Path = "ImGui"}}

[Workspace]
StartupProject = "ImGuiExample"
